### ISSUE TITLE
add flag to boostrap.py to specify what you want, dev, stable, etc

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#104]
We had problems at the sprint because by default boostrap gets the master version. For development, we want to default to the develop branch. 

So we should add a new virtualenv flag to allow that.

**Comment by brondsem** [comment]
I think bootstrap.py defaults to develop, but people were checking out master when they weren't following the bootstrap.

**Comment by mitechie** [comment]
Bah, you're right. I assumed if you were going through the manual install steps at this point you'd be doing more up to date/dev version than the stale master releases. I think the better todo is just to tackle the install/setup docs a second time and try to clear things up better.

**Comment by brondsem** [comment]
By the time I figured it out, I had a patch anyway, so here you go :)

**Comment by mitechie** [comment]
Ok, awesome.

**Comment by mitechie** [comment]
Changed merged, pushed the updated bootstrap.py to docs.bmark.us for use.
