### ISSUE TITLE
access my bookie install from browser extension

### ISSUE THREAD

**Issue by widox** [bookieio/Bookie#111]
Would be nice if there was an option on the browser extension to open my bookie install in a new tab. Maybe in the right click menu, or if I left click the extension icon when on a blank tab it opens my bookie page.

**Comment by mitechie** [comment]
We can add a right-click to open your bookie instance to the right-click menu where the "Read Later" option currently is. I don't think there's much to be done about changing the function of the extension on the "new tab" blank tab vs a page.

**Comment by mitechie** [comment]
I think the best thing is to work on adding it as another keyboard shortcut along side the one we already use.

https://github.com/mitechie/Bookie/blob/develop/extensions/chrome_ext/shortcut.js

We would add it there. What's everyone's idea for an unused key binding? ctrl-meta-d?

**Comment by mitechie** [comment]
We've added an icon to the upper right of the extension that links directly to your bookie install. There's not a keybinding, we can look at that later, once the chrome keybinding bits land. For now though, this is a start to allow opening up your install fairly quickly.
