### ISSUE TITLE
check out tagger library as a way to provide tag suggestions

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#119]
https://github.com/apresta/tagger

The trick here is going to be performance, and the need to send the document to the server to be parsed for suggested tags. 

Might need to provide a background task in the chrome extension so it loads quickly, but tries to get tag suggestions while you're filling it out? 

Might just provide it on the readable page to start. When you're reading, provide suggestions for other tags and make it easy to one-click add them to the stored bookmark.

**Comment by rakeshmahadasa** [comment]
Working on it :+1:

**Comment by mitechie** [comment]
This is working on the edit page and needs some love to avoid some poor suggestions like () and such. There's another branch that does some work that suggests only nouns we might be able to merge back in. The other branch is working on providing some hints for suggestions. So this is well under way. I'll leave it open for now, but soon I think we should close this and open fresh issues for optimizing the new code vs this origin issue of 'add feature'

**Comment by mitechie** [comment]
This is basically implemented minus some fleshing out and bugs. Closing this issue and working with new ones that are specific to missing features/bugs around the task.
