### ISSUE TITLE
Edit page does not show existing tags for editing or deletion

### ISSUE THREAD

**Issue by icheyne** [bookieio/Bookie#120]
1. Go to your bookmarks page - https://bmark.us/username/recent
2. Click an edit link for a bookmark with existing tags
3. The existing tags are not shown - so you cannot edit or delete them

Firefox 6.0.1

**Comment by mitechie** [comment]
Thanks for the report

It appears that the tag_str field isn't getting populated since the move to the new fulltext codebase. I'm currently revamping to use the updated SqlAlchemy 0.7 events vs the old mapper extension version. I should have an update tonight/tomorrow.

**Comment by icheyne** [comment]
Thanks for the quick fix, but there's another bug. :o( #121

**Comment by mitechie** [comment]
Sorry, git closed this. It's getting deployed right now. The db update is hammering things and slowing it down at the moment.
