### ISSUE TITLE
Edit page shows random tags

### ISSUE THREAD

**Issue by icheyne** [bookieio/Bookie#121]
1. Go to https://bmark.us//username/recent.
2. Note the tags on a bookmark
3. Click the edit button for that bookmark

The tags will not relate to the bookmark. 

P.S. it's really slow right now.

**Comment by mitechie** [comment]
Thanks, I'm currently working on the tags for the #120 bug and will see what's going on. There's currently a database migration going in to update things atm.

**Comment by mitechie** [comment]
Bah, this is what happens when you leave off a where clause in a db migration. I've made the migration fix and restarted it. Should be corrected shortly.

**Comment by mitechie** [comment]
migration complete. Speed should be back to normal. All tags in edit should now show correctly.

Thanks for the report and patience for my mistake! :-)

**Comment by icheyne** [comment]
Bug fixed and the site is working quickly. Thanks!
