### ISSUE TITLE
Cannot delete bookmarks

### ISSUE THREAD

**Issue by icheyne** [bookieio/Bookie#123]
I cannot see how to delete bookmarks, either on the edit page or the bookmarks lists.

Firefox 6.0.2

**Comment by mitechie** [comment]
Thanks, this is something that needs to be implemented. It's available in the chrome extension, but since you're using through firefox you don't have an easy way to hit it. 

I'll work on getting something there by the end of CHC on wed. The api for removing a bookmark is there so we just need to add the button back into the list view and run some client side JS to make sure you want to remove things and remove the row from the live view.

**Comment by icheyne** [comment]
Thanks for looking at this. I'm relieved. I thought I was going crazy when I could not see it in the UI. I switched off adblock, noscript etc, but I still could not find it.

**Comment by mitechie** [comment]
Just an update, along with this came along the idea that the ui needs an update to be a bit more friendly to edit controls and such ootb. 

See ticket: https://github.com/mitechie/Bookie/issues/129

The work on getting a proper delete functionality is going to be part of that. It'll be a total client side driven UI and the controls for delete and such will work through the backbone.js models created to power the view. 

You can view progress in the branch: https://github.com/mitechie/bookie/tree/feature/jsui

I'll try to get a 'test' url onto the live site once I get close to feature parity (right now there's no paging/etc in the view)

**Comment by icheyne** [comment]
Thanks Rick. I'll help test.

**Comment by mitechie** [comment]
The http://dev.bmark.us has been updated with the work on the new ui so far. The delete feature is implemented in that development branch/test url. 

You can test it out and see it working by logging into the site as admin/admin. Once logged in, the new controls are on the right end of each bookmark. Click the X to delete and the row should disappear.

**Comment by icheyne** [comment]
I tried it and it's not working right now. I'll give it a go later.

**Comment by mitechie** [comment]
If you get a sec, hop in irc #bookie and let me know what didn't work. You have to log into the admin account in order to get the delete option (can't delete anyone else's bookmarks)

Thanks

**Comment by icheyne** [comment]
Unfortunately my office blocks IRC and I'm busy tonight.
1. I logged in.
2. Went to My Bookmarks
3. Clicked the \* link next to a bookmark.

Nothing happened

**Comment by mitechie** [comment]
Thanks for trying. There is some bug I've hit with uwsgi and the application. If I run it with paster or gunicorn it succeeds. 

For now I've changed the server over to gunicorn and things appear to be working. Give it a shot when you get a sec and let me know if you hit anything else.

**Comment by icheyne** [comment]
Yes it works now. Much slicker. :)

**Comment by mitechie** [comment]
Delete it now working via the new Ajax UI. Once logged in each bookmark has an X on the right to delete.
