### ISSUE TITLE
per user timezone support

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#127]
I just noticed that a bookmark I saved last night before bed (11pm-ish) is showing up as from today. This is because I'm a weirdo in the Pacific timezone not eastern.

**Comment by mitechie** [comment]
bah, I knew this would come up :)

**Comment by mitechie** [comment]
So I've pushed an update that stores all date/times in UTC and the new 'days ago' will take into account the client's timezone when converting. It's only for new bookmarks moving forward so give it a go and let me know if this completes this for you. If not, reopen and I can look into it more.
