### ISSUE TITLE
Need Link to Bookie Chrome Extension in Account

### ISSUE THREAD

**Issue by brousch** [bookieio/Bookie#132]
I would like a link to the correct (for the install I'm using) version of the Chrome Extension on the Account page, probably near the Bookmarklet stuff. Or maybe move the Bookmarklet and Chrome Extension to a Tools and Stuff tab. Plzkthx

**Comment by mitechie** [comment]
There are now links in the account page for the extensions. New users also get a link when they load their empty page of bookmarks.
