### ISSUE TITLE
JavaScript error when deleting duplicate tags from tag input

### ISSUE THREAD

**Issue by waf** [bookieio/Bookie#136]
1. Load bmark.us
2. Enter the tag 'python'
3. Enter the tag 'python' again
4. Press the backspace button twice

Error received:

Uncaught TypeError: Cannot call method 'destroy' of undefined
ns.TagControl.Y.Base.create._parse_inputcombo:18
f.notifySubcombo:9
b.Subscriber.notifycombo:9
b.CustomEvent._notifycombo:8
b.CustomEvent._procSubscombo:8
b.CustomEvent.fireSimplecombo:8
b.CustomEvent.firecombo:8
r._createWrapper.C.fncombo:54

**Comment by mitechie** [comment]
Changed the tagcontrol to check for dupes when adding so that we can't get this situation.
