### ISSUE TITLE
When the bookmarked page does not contain a title, there is nothing easy to click on

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#137]
See https://bmark.us/greg/recent (right now at least)

Or, to test, bookmark a page without a title, eg: http://schema.rdfs.org/all.json

That shows up without a title in Bookie's list, thus there is no easy clickable link to get to the page (I have to copy/paste the url).

**Comment by mitechie** [comment]
Thanks for the heads up. I think adding a conditional check to the template used to render would be handy. 

https://github.com/mitechie/Bookie/blob/develop/bookie/templates/jstpl.mako#L8

An example conditional would be such as:

https://github.com/mitechie/Bookie/blob/develop/bookie/templates/jstpl.mako#L16

**Comment by mitechie** [comment]
This fix is released. If there's no description then it just places ----- in its place. It doesn't set a default and if you edit you'll see no description in the field. It's just in the template for displaying bookmarks. If you think something else would be better I'm open to it, but didn't want to have real text such as "No description available" as I think that'd be more distracting when reading down the page.

**Comment by greggrossmeier** [comment]
Only other thing I could think of is doing something like "[No Title]" (pinboard's method). Or, new delicious' method of just repeating the URL (http://www.delicious.com/greg.grossmeier).

**Comment by mitechie** [comment]
Ah, I should have thought of putting the url in there. Any preference on what you'd rather see Greg?

**Comment by greggrossmeier** [comment]
Personally, [No Title] would be my preference. But you didn't like how that looked, so, either that or the URL repeated.
