### ISSUE TITLE
Tag control should activate tag on focus lost

### ISSUE THREAD

**Issue by widox** [bookieio/Bookie#141]
When saving or editing a bookmark, it only saves a tag if I've used it previously. This is from both the Chrome extension and the website. I don't see any errors or anything, it just doesn't save.
Also, the new tag word doesn't turn into a grey box like an existing tag does.

Using Chrome Version 19.0.1055.1 dev
Extension Version 0.4.3

**Comment by mitechie** [comment]
Can you provide a few details on which bookmark you were trying to edit and what tag you were adding? I've tested editing an existing bookmark and I can add a tag not on it as well as a generic new tag that's never been used on the site. 

Now, I did notice that if I didn't trigger the tag control (hit space or tab or what not to have it "grey box" the tag) that it didn't get saved. So I think it might be a case of clicking on submit not triggering the tag control to register the tag. 

If you get a chance to try again, please edit the same bookmark with the same new tag, but make sure to hit space so the tag 'registers' in the control.

**Comment by widox** [comment]
Ah yep, hitting space after the new tag name grey boxed it and was saved.
Maybe triggering that same event when hitting save would lessen the confusion.

**Comment by mitechie** [comment]
Yea, so the tagcontrol should watch for the focus lost event on the input control and if there's non-empty text, fire the add event on the tag control. Will add to the todo.
