### ISSUE TITLE
hard to copy/paste tags in web edit

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#149]
I'm editing a bookmark of mine that doesn't have tags (unheard of!) I wanted to simply reuse the same tags as another bookmark.
So I;

1) Went to my /recent page and selected the text of the tags and copied it into my clipboard
2) Went to the edit page of the bookmark without tags and pasted the text into the tag textbox
3) It (the web edit view) turned it into one big tag :(

This is the text in question, which is simply some words separated by spaces:
open-source blackboard lms fauxpen community moodle floss sakai community-management drchuck

**Comment by mitechie** [comment]
Right, the TagControl widget should also respond to the paste event in the control. It currently doesn't. During paste, it should read the text, split, and handle updating the widget.

**Comment by mitechie** [comment]
Deployed an update to parse/fix text with multiple tags. The one thing I did do was to not auto make the last one a tag. Let's say you copy/paste something incomplete, it leaves the last tag in edit mode and you have to <space> or <enter> to complete the tag selection.
