### ISSUE TITLE
Database is sqlite3 specific

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#15]
Tried using bookie with postgresql, but unfortunately the migrations create a virtual table for fulltext searching, which doesn't have an equivalent in postgresql.

**Comment by mitechie** [comment]
Yea, need to figure out how to make the relationship a manual one that we can check for the engine used and only apply it if necessary. Same with the migration, to only add the table if you're using sqlite.

**Comment by mitechie** [comment]
Abstracted and updated to make it check for sqlite and mysql for fulltext support. Seems to be working ok and cleaned up. 

Should be able to add postgresql support now without too much fuss since the pain points have been worked out.

**Comment by mitechie** [comment]
Pushed the pgsql changes to develop. We're now good with all three supported dbs, sqlite, mysql, pgsql.
