### ISSUE TITLE
icon font fails to render in FF nightly

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#153]
http://grossmeier.net/files/tmp/Fx_nightly.png

The icons are all unicode blobs. They should be pretty icons. Check the formats served in the font and if FF accepts them/needs something in the css tweaked.

**Comment by greggrossmeier** [comment]
Btw, I confirmed this on both Debian Wheezy and Ubuntu 11.10 with Fx nightly. Both look exactly like the linked screenshot.

**Comment by mitechie** [comment]
See http://stackoverflow.com/questions/11072655/firefox-font-face-fail-with-fontawesome for the gory details. PyScss broke me a little bit.
