### ISSUE TITLE
[Feature] Append private bookmark in Bookie

### ISSUE THREAD

**Issue by harobed** [bookieio/Bookie#187]
Append private bookmark in Bookie, only user logged can see its private bookmark.

Regards,
Stephane

**Comment by mitechie** [comment]
There's some corresponding work for this under the command system, see issue #36

https://github.com/mitechie/Bookie/issues/36

The idea is that the private bookmarks would be added via the !private tag during saving.

**Comment by mitechie** [comment]
This is a very popular GSoC project and will hopefully be something worked on in the near future. Leaving the issue open, but if a student working on this is selected will close this and turn it into work items for the student vs the open bug.

**Comment by mitechie** [comment]
This is nearly complete. We're working on bringing up a new server with the latest source code but the work for this has landed. Once the new site goes live we'll release updated extensions to support it.

**Comment by mitechie** [comment]
This is now released. Closing bug. Phew that was a long way to go. Thanks Sam and GSoC!

**Comment by anarcat** [comment]
i wonder how / when that functionality will be accessible from the chromium / firefox plugins?

**Comment by mitechie** [comment]
They both have commits to them to enable the functionality. I had hoped to release them on the same day as the server update, however bugs/issues slowed that down. My hope is to get those tested and released this week.

https://github.com/bookieio/bookie-chrome/commit/d8394c02f0234871ff2d69c60e67edd6d1cc938d
https://github.com/bookieio/bookie-firefox/commit/feea7aa1e50b55e248f35ed7ef9e25a422313132

If anyone wants to download and test out the builds I'd love to have some additional QA and assurance the plugins are fine and ready to go.

**Comment by mitechie** [comment]
FYI the extensions are released. The chrome one is updated and on 0.5. I've submitted the Firefox one as well but it has to go through the review process before getting updated and I'm not sure how long it'll take.
