### ISSUE TITLE
[Feature] Append a variable flag in .ini config file to switch Bookie in single user mode

### ISSUE THREAD

**Issue by harobed** [bookieio/Bookie#188]
Append a variable flag in .ini config file to switch Bookie in single user mode.

Why ? I would like append Bookie instance in my personal website.

In single user mode :
- hide signup feature
- in home page, go directly to all bookmark page
- change the title of "All" bookmark to "Username bookmarks"

What are your comments ?

Best regards,
Stephane

**Comment by mitechie** [comment]
This is possibly ok. I think I'd do this in baby steps to see how much was required in an effort to keep the differences as small as possible. 

Step #1 would be to add a flag to enable/disable signups. From there we can look at the tweaks that make sense in a single user mode.

**Comment by harobed** [comment]
I would like work on this task.

**Comment by mitechie** [comment]
As bookie works ok in a single user world, there are just odd corners, and the devs aren't interested in testing and maintaining a single user world I'm closing this bug. I apologize, but as a part time project, sometimes you have to cut scope to keep things as easy to maintain as possible.
