### ISSUE TITLE
Feature Request: Include breadability version of page in RSS body

### ISSUE THREAD

**Issue by brousch** [bookieio/Bookie#193]
Include the breadability version of the page in the RSS post body. Right now it's just the title.

**Comment by mitechie** [comment]
This is dependent on getting issue #142 fixed since it doesn't allow us to do a full nice query joined across the readable content currently.

**Comment by mitechie** [comment]
because of the limited number of results in the rss field though, perhaps we can do this as a more expensive multple query option.

**Comment by mitechie** [comment]
I've updated and deployed the bodies into the rss feed. It's placed into the summary atom field, however I notice in using feedparser the body comes out in the feed.entries[0].content attribute. I'll see how it looks in newsblur. Please check your rss reader and let me know if it's not working correctly and we can tweak.
