### ISSUE TITLE
user based click count isn't processed

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#196]
I a url is clicked on from a user's home page, it should increment the global count on that bookmark as well as the user one.

so /admin/redirect/hashid

should increment two different counters. 

This currently fails, perhaps because the routes should be in reverse order, going from most specific to least. If we always hit the first route it never populates the {username} in the matchdict.

**Comment by kshitijiiit** [comment]
I am currently working on this.

**Comment by kshitijiiit** [comment]
Solved!
