### ISSUE TITLE
Bookie Chrome Extension does not notify if you aren't logged in

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#201]
The Bookie Chrome Extension will appear to hang if you have not updated your settings (changed API key, moved to a different machine / profile, etc.). It would be more helpful if there was a way to determine the user had not configured the extension, and present either a message "you need to configure", or some marker on the icon. 

I'm not sure if this also happens if you have the wrong information in the extension.

**Comment by suryatech** [comment]
Working on this.

**Comment by mitechie** [comment]
This is released as 0.4.15
