### ISSUE TITLE
Chrome ext doesn't save bookmarks

### ISSUE THREAD

**Issue by oandregal** [bookieio/Bookie#202]
I'm using Cromium 18.0.1025.151 (Developer Build 130497 Linux) Ubuntu 10.10. After installing the extension and bookmark a webpage I see the processing icon going. After it stops I go to my bookmarks in https://bmark.us/amaneiro/recent but they aren't updated.

Besides I see a void bookmark have been created, don't know if it may be related with the issue.

**Comment by craigmaloney** [comment]
One thing to check is that you are logged in to the extension. I've had several instances where I thought I was logged in, but wasn't. The extension will act as though it's saving, but eventually if the extension loses focus, it'll close the progress window leaving you to believe something was successful.

The best way I've found to check if you're logged in is to attempt a sync under the Bookie Extension's Options menu.

Also: make sure you're using the API key, not the password for the site.

Hope this helps!

**Comment by oandregal** [comment]
That's it! Thanks :) PS: sorry for the noise
