### ISSUE TITLE
make stop leaves billard running

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#205]
After starting with "make run" and then "make stop" I find that billard is still running. Everything else stops just fine.

I'm running on Debian 6.0.7 using python 2.6.6.

**Comment by mitechie** [comment]
Can you verify that this is always the case? I've definitely found that sometimes shutting down celery with the pid file  doesn't also catch billiard, but sometimes it does. I should try an updated celery release or maybe the way we're killing celery is poor. So far I've blamed celery for the left over process.

**Comment by jpschewe** [comment]
No, this isn't always the case. I got everything up and running cleanly tonight and then running "make stop" stopped everything. I'll keep watching for it to break again and see if I can fix it.
