### ISSUE TITLE
Activate link doesn't have any action associated with it

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#206]
I built the develop branch on Debian 6.0.7. I went to the main page and put in my email address. I received a link that I visited. I was then prompted for my username and password. I entered both and clicked the Activate button and nothing happened. I checked my javascript console and didn't see any errors. I checked the source and don't see a handler attached to the Activate button.

**Comment by mitechie** [comment]
The form there is bound in the views.js via the AccountResetView. It's bound to the form 'submit' action. It does the api call to activate the account and should show a message in green text saying it's been activated. There's a bug (#150) currently about improving the login process so that once you activate it takes you to your account logged in, but it's not been implemented yet.

Did the account work? I wonder if the green text wasn't noticeable or if it didn't work and the account wasn't activated or something else?

**Comment by jpschewe** [comment]
I didn't get any green display. Clicking the activate button appears to do nothing. Attempting to login with the username and new password results in a failed login message.

I found this in the paster output

``` sh
serving on 0.0.0.0:6543 view at http://127.0.0.1:6543
/home/jpschewe/projects/Bookie/lib/python2.6/site-packages/sqlalchemy/engine/default.py:455: SAWarning: Unicode type received non-unicode bind param value.
  param.append(processors[key](compiled_params[key]))
2013-04-14 22:35:31,605 ERROR [bookie.views.auth][worker 3] CHECKING
[E 130414 22:35:31 auth:180] CHECKING
2013-04-14 22:35:31,605 ERROR [bookie.views.auth][worker 3] jpschewe@mtu.net
[E 130414 22:35:31 auth:181] jpschewe@mtu.net
2013-04-14 22:35:31,612 ERROR [bookie.views.auth][worker 3] jpschewe@mtu.net
[E 130414 22:35:31 auth:191] jpschewe@mtu.net
2013-04-14 22:35:31,612 ERROR [bookie.views.auth][worker 3] jpschewe@mtu.net
[E 130414 22:35:31 auth:192] jpschewe@mtu.net
```

**Comment by jpschewe** [comment]
Where would views.js be? I looked for it and can't find it:

``` sh
jpschewe@mtu:~/projects/Bookie
[git:develop] >find . -name views.js -print
jpschewe@mtu:~/projects/Bookie
```

**Comment by jpschewe** [comment]
I thought of something, what ports does the website need to talk to on the host? I'm actually building this on a remote system and using port forwarding to access the pages until it's ready to go live. I've just been forwarding port 6543, however looking at the HTML source this morning I also see some references to port 8000. Are there other ports needed as well?

**Comment by mitechie** [comment]
On Mon, 15 Apr 2013, Jon Schewe wrote:

> I thought of something, what ports does the website need to talk to on the host? I'm actually building this on a remote system and using port forwarding to access the pages until it's ready to go live. I've just been forwarding port 6543, however looking at the HTML source this morning I also see some references to port 8000. Are there other ports needed as well?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mitechie/Bookie/issues/206#issuecomment-16380670

Yes, the combo loader that serves javascript is on port 8000. It's the make
run_combo and without it the javascript would fail to load. There should be
failed requests in the browser network list.

Rick

**Comment by jpschewe** [comment]
It was the missing port forward. Once I forwarded localhost:8000 then the activate link works.

**Comment by mitechie** [comment]
Cool! Glad it's working for you. Normally when you host things get put behind a proxy in nginx/apache and so the two ports turn into the one based on urls.
