### ISSUE TITLE
List of tags

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#213]
It would be nice if there was a list of tags for browsing.

**Comment by mitechie** [comment]
There actually is. It was removed from the nav because the UX on it is pretty crummy and it needs to be rethought. 

https://bmark.us/tags for instance is the list of tags on bmark.us. It'll take a while to load though as it's not paginated and all that.

**Comment by jpschewe** [comment]
I see this works nicely. If I just put that in the sidebar that would be
excellent.
https://bmark.us/jpschewe/tags

On Mon, May 27, 2013 at 6:27 PM, Rick Harding notifications@github.comwrote:

> There actually is. It was removed from the nav because the UX on it is
> pretty crummy and it needs to be rethought.
> 
> https://bmark.us/tags for instance is the list of tags on bmark.us. It'll
> take a while to load though as it's not paginated and all that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mitechie/Bookie/issues/213#issuecomment-18517987
> .

## 

http://mtu.net/~jpschewe
