### ISSUE TITLE
URL is not added automatically

### ISSUE THREAD

**Issue by alexgalkin** [bookieio/Bookie#214]
Extension does not include current URL that should be saved (only title is pre-populated)

**Comment by mitechie** [comment]
Can you provide details on what url you were attempting this with? I've not seen this bug and we've got a few users of the extension. I wonder if there's something specific in the url encoding or something that caused this.

**Comment by alexgalkin** [comment]
No URLs are pre-populated. Even URL to github (e.g. https://github.com/mitechie/Bookie/issues/215)

Unfortunately I cannot attach screenshot. I am using Google Chrome Version 27.0.1453.110 m (the latest one). Once I click on extension button I received pop-up with pre-populated title but URL and Notes are empty.

**Comment by mitechie** [comment]
Ok, looking how can you tell the url isn't loaded in the chrome extension? It's not actually visible. The url is in a hidden field, the title is pulled. The next box is for you to enter tags and the last one is for notes. Both the tags and notes will start out empty unless you fill them in.

If the extension isn't working correctly double check that you've right-clicked, gone into options, and filled our your usename and api key. You can verify that it's correct by clicking on 'sync' and not getting an error.

**Comment by alexgalkin** [comment]
Oops, apologize for confusion. I have missed that step with Settings. You should probably add placeholders to input fields to indicate what are they for and mention Settings at the bottom. Thanks.

**Comment by mitechie** [comment]
Thanks for checking. Yes, the extension needs some better UX love. There are a couple of bugs right now about having the extension be smarter about letting you know when the settings aren't correct. Once you get into the "options" pane it does a sanity check that the settings are valid, but that's not carried out to the main bookmark page yet. :(

Sorry it caused you some wasted time today.
