### ISSUE TITLE
Hosting documentation doesn't talk about celery

### ISSUE THREAD

**Issue by jpschewe** [bookieio/Bookie#216]
To actually get email confirmations sent out you need to start celery. The hosting documentation at http://docs.bmark.us/en/latest/hosting.html doesn't mention anything about this. I figured it out from the Makefile.

I put the following script in the root directory to execute

``` sh
#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"


cd "${mydir}"
PYTHONPATH="bookie/bcelery/." 
export PYTHONPATH
BOOKIE_INI=production.ini
export BOOKIE_INI

CELERY="bin/celery worker -B --app=bookie.bcelery.celeryd:celery --loglevel=DEBUG"
${CELERY} --pidfile celeryd.pid 
```

**Comment by mitechie** [comment]
Thanks, I'm hoping to get rid of celery soon. I'm currently working on getting rid of the combo loader dependency and next up will be a different/lighter weight job system. I'll try to get this into the docs for now to help out current users. Thanks for submitting the script you used!

**Comment by jpschewe** [comment]
Getting rid of both would be nice, less machinery to keep track of.

**Comment by mitechie** [comment]
Yep, that's the plan. The branch with the combo loader removed is located here https://github.com/mitechie/bookie/tree/empty-bmark-199 (got sidetracked while working on the empty bookmark bug)

**Comment by mitechie** [comment]
The docs mention celery now. The negative is that we've kept celery and moved to using redis and some of its features. 

One thing I noticed was that the auto expiring return values in celery didn't like older versions of redis and I had to update it using a PPA to 2.6.X version.
