### ISSUE TITLE
Cache / save pages linked  in the bookmark

### ISSUE THREAD

**Issue by lightonflux** [bookieio/Bookie#218]
Sometimes when you bookmark a blog post, one essential part of the bookmarked blog entry are the sources linked in the article. Sadly, many of these links break or just disappear from the web. Therefore it would be great if Bookie had an option which sends every link linked in the cached version of the page trough the readability function.

In ascii art:

```
+---------------+        ###################
|  Orig. page   |    ⇒   # Added to Bookie #   ⇒  
+---------------+        ###################     ⇩
                                                 ⇩
==================            ***************    ⇩
= Searches links =     ⇐      < Readability >  ⇐
==================            ***************
        ⇩
+--------------+
| Linked pages | +           ***************
+--------------+ | +    ⇒    < Readability >
 +---------------+ |         ***************
  +----------------+              ⇩⇩⇩⇩
                                  ⇩⇩⇩⇩
                       ٩(⁎❛ᴗ❛⁎)۶٩(⁎❛ᴗ❛⁎)۶٩(⁎❛ᴗ❛⁎)۶
                            Happy archivists
```

PS: Some Unicode characters are involved.

**Comment by mitechie** [comment]
This is an interesting idea. It would require two parts. breadability would need to be updated to provide suggested 'related links' found when parsing the page as part of the metadata payload and then Bookie would take those links and auto add them as additional bookmarks. 

I'll mark this as wishlist for now, but it would be cool to have that kind of self-building bookmark network.

**Comment by mitechie** [comment]
After thinking about this a lot, I think this really is a different service than Bookie. I think an app that, given a url, could parse and grab the other content could be useful. It could use breadability and other libraries of code in Bookie, but it doesn't fit into the Bookmark use of Bookie itself. There's too many questions of how to handle the linked content. Is it searchable even though you didn't bookmark it? Are they auto tagged some way? Are they hidden from view? What about the links in those pages? I'm going to close this for now. As Bookie matures, there might be something in here to look at adding, but right now it's not a fit I can see getting into place smoothly.
