### ISSUE TITLE
Alias tags

### ISSUE THREAD

**Issue by lightonflux** [bookieio/Bookie#220]
Sometimes it's hard to refind bookmarks, for several reasons. 

E.g. i have the problem with tech articles, because many of them are in english and that's not my native language. When i try to refind something it can happen that i search for the wrong tag/key word like command (for english articles) vs. befehl (german articles)/ cli vs shell. Or just two terms / abbreviations for the same thing e.g. FOSS vs FLOSS or USA vs united staates.

So wouldn't it be great if you could use aliases like in Bash and other shells?

So when you search for FOSS you will also get results for FLOSS. And when you tag something with "extensions" Bookie will automatically assign the tag "erweiterungen" (same thing in german) because the user defined it.

This whole thing could be solved by disciplined users, but let's be honest who is disciplined enough to make up his own tagging system for different languages, abbreviations and sticks with it the whole time?

**Comment by craigmaloney** [comment]
This sounds like an interesting idea, though I'm not sure how it could be implemented under the current framework. Perhaps a separate look-up table with the original tag, and a bunch of other tags that are aliases for it? But then there comes the question of when you want to promote an alias to a main tag. How would that work?

**Comment by mitechie** [comment]
Thanks for the idea. I completely agree that sometimes we don't use the tags when we bookmark something that we think of later when looking for it. That was one of the biggest reasons to support fulltext search. I think that'll best fallback we can use for now until we can get to some sort of automatic tag suggestions into place.
