### ISSUE TITLE
import new delicious format 

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#238]
Looks like we're getting imports from a new xml based format from delicious. We need an importer for it asap.

**Comment by mitechie** [comment]
http://lifehacker.com/5136845/backup-delicious-bookmarks-from-the-shell

Maybe help to get a copy of the new format.

**Comment by mitechie** [comment]
Fixed, released and imported the two users that hit it today.

**Comment by lxneng** [comment]
:thumbsup:
