### ISSUE TITLE
Search API doesn't filter by user

### ISSUE THREAD

**Issue by fitztrev** [bookieio/Bookie#251]
Adding the username to the URL doesn't filter the results.

https://bmark.us/api/v1/bmarks/search/bookmarks
https://bmark.us/api/v1/admin/bmarks/search/bookmarks

**Comment by mitechie** [comment]
Hmm, you're right. Looking at the code, we intentionally set it to None if it's not your username. 

https://github.com/mitechie/Bookie/blob/develop/bookie/views/api.py#L478

I'm not recalling why this was.

**Comment by mitechie** [comment]
In looking at this today I remember why now. The UI on the website has a single search link. You're doing a global seach. What should happen is the UI should add an input/checkbox for 'only search my bookmarks' so that we can distinguish the two cases of global search and user specific search.

**Comment by mitechie** [comment]
I've updated the logic in the view code to build/pass the username but the query executed in the fulltext isn't setup to actually use it. It'll need another follow up branch.

**Comment by mitechie** [comment]
This landed and is deployed.
