### ISSUE TITLE
Readable page doesn't have title of content

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#273]
Example: https://bmark.us/bmark/readable/3467f263dbe385

Would be nice to have the title of the page so when I print it out (save as PDF, actually) it would use the title for the filename.

**Comment by mitechie** [comment]
How does it not have the title? It's there on the page?

**Comment by mitechie** [comment]
or do you mean the html page title so that the browser prints it in the margin up top?

**Comment by craigmaloney** [comment]
Yeah, it's the title at the top of the HTML page. Was hoping it would
more closely match the title of the content of the page, not the site
itself.

**Comment by mitechie** [comment]
Landed and pushed live.
