### ISSUE TITLE
Users should have a delete button for their bookmarks

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#274]
When a user mistakenly imports something they did not intend to be public or decides they don't want their data in the bookie install any more we should let them delete their account/data.

**Comment by carpedm20** [comment]
I think there is already delete features in account/recent page. Do you mean a page which will be shown right after a user import a .html file and display only imported bookmarks to select which bookmarks will be deleted or not? Or do you mean another features?

**Comment by mitechie** [comment]
This is meant to be a global delete. From a user's account page should be a "delete all of my bookmarks" button so that they can remove all their bookmarks from the system in one swoop.

I'd imagine that this would then fire off a background job in bcelery/tasks to do the actual work of removing the users bookmarks from the system in batches.

**Comment by preddy5** [comment]
I am currently working on this bug

**Comment by kshitijiiit** [comment]
Solved.

**Comment by mitechie** [comment]
Fix released.
