### ISSUE TITLE
Problem in installation of bookie

### ISSUE THREAD

**Issue by aka001** [bookieio/Bookie#279]
In the command:
make sysdeps
If you have an old virtual machine or the folder is in a folder which has a space in between it like "Ubuntu One" then it fails to download all packages.

**Comment by aka001** [comment]
The old virtual machine problem can be resolved by installing a new one.
And the directory can be renamed to a non-space directory. After this follow the whole process again(starting from cloning the repository).
A fix for the spaced directory is needed however.

**Comment by mitechie** [comment]
Thanks for the report. You're right that a space in the path will cause issues. The Makefile needs to be updated to quote paths to avoid this.

**Comment by aka001** [comment]
Okay. :)
