### ISSUE TITLE
[GSoC] Google Cloud Platform port

### ISSUE THREAD

**Issue by frederikcreemers** [bookieio/Bookie#307]
I'd love to port Bookie to the Google Cloud Platform, so that people who want to run it there can run it there.

I'd keep the complexity of setting it up, and the price of running it on the cloud platform low, or even zero, by only relying on app engine, and no other cloud platform services outside App Engine.
I'd have to change the model layer from SQLAlchemy to app engine's ndb.

Background tasks such as social network monitoring can easily be handled by the app engine task queue or cron jobs.

I'll also submit this as a proposal on the GSOC site once student applications open.

**Comment by mitechie** [comment]
On Wed, 26 Feb 2014, Frederik Creemers wrote:

> I'd love to port Bookie to the Google Cloud Platform, so that people who want to run it there can run it there.
> 
> I'd keep the complexity of setting it up, and the price of running it on the cloud platform low, or even zero, by only relying on app engine, and no other cloud platform services outside App Engine.
> I'd have to change the model layer from SQLAlchemy to app engine's ndb.
> 
> Background tasks such as social network monitoring can easily be handled by the app engine task queue or cron jobs.
> 
> I'll also submit this as a proposal on the GSOC site once student applications open.

This is an interesting idea Frederik. I think there's a bit more to this
than meets the eye. Alembic is used for database migrations, which is based
on SqlAlchemy. The bookmarks are sent and updated in the fulltext index via
SqlAlchemy's event infrastructure.

While I don't think the team is opposed to enabling more people to use
Bookie on their platform of choice, too much upheaval in the code base would
be hard to swallow without a large gain on the other side. Maintaining that
would be tough as well.

I think the team is open to listening to your proposal, but I'd love to see
some specific details on how we'd keep both the current feature/support in
place around this app engine specific updating. I'm not sure it would work
out.

## 

Rick Harding
@mitechie
http://blog.mitechie.com
https://bmark.us

**Comment by frederikcreemers** [comment]
Thanks for your quick reply.

This might be a hard one.

I'd have to dive deeper into the codebase to see exactly how this would be
implemented, but it could work the same way a lot of other cross platform
projects are developed. There is one folder for common code, that uses high
level abstractions to model the bookmark storage, user storage,... Then,
there would be folders for platform-specific code that implements these
services on top of the technologies available on that platform, and there
would be a build script that puts together distributions for the platforms
based on the common and platform specific directories.

It's a lot of work, but I think I can do it in the timespan of gsco.

**Comment by mitechie** [comment]
Closing this out for now. The proposals for projects will be done on the GSoC site.
