### ISSUE TITLE
Make Bookie archlinux compatible (or even distro independent if possible)

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#310]

**Comment by dyladan** [comment]
here are the ubuntu dependencies installed in the makefile and their archlinux counterparts. would be nice to make it distro independent in the future if at all possible

UBUNTU
build-essential libxslt1-dev libxml2-dev python-dev libpq-dev git python-virtualenv redis-server unzip

ARCHLINUX
base-devel libxslt libxml2 python postgresql-libs git python-virtualenv redis unzip

**Comment by sanchitgangwar** [comment]
Looking into it.
