### ISSUE TITLE
502 bad gateway on submitting import form without a file to upload

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#311]
I think it is related to this file but since i have very little python and even less pyramid i'm not sure

https://github.com/bookieio/Bookie/blob/develop/bookie/views/utils.py#L58

**Comment by sambuddhabasu** [comment]
I am currently working on this bug.

**Comment by preddy5** [comment]
@sammyshj hey im already working on it

**Comment by sambuddhabasu** [comment]
@pradyu1993 Sorry, no one had commented on this bug, so I had started working on it. Already done with the patch. Testing that nothing breaks. Will be done with the pull request in a while.
I guess it would be good if you start working on some other issue :)

**Comment by mitechie** [comment]
Landed
