### ISSUE TITLE
create a dockerfile

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#316]
add a dockerfile to the repository that would create a docker container with all dependencies already installed. This would have the advantage of ensuring a consistent development environment across platforms and remove the need for any sort of dependency installation. Instead of running a magic make command that installs things on your computer you could just run `docker build github.com/bookieio/Bookie`.

**Comment by mitechie** [comment]
Very cool idea. I think it'd be cool to have some something light like that to getting started.

**Comment by dyladan** [comment]
I'm working on it right now actually. you might not have to wait for the weekend

**Comment by dyladan** [comment]
as it turns out. docker only runs on 64 bit machines. since my laptop is 32 this is a deal breaker for me. somebody else can still work on this though or @mitechie can close it

**Comment by mitechie** [comment]
Will close for now. Interesting feature and might be useful for some users, but it's so far down the todo list for the current dev team.
