### ISSUE TITLE
stats/bmarkcount api endpoint fails when specifying the start_date param

### ISSUE THREAD

**Issue by widox** [bookieio/Bookie#329]
I tried hitting this API endpoint:
`https://bmark.us/api/v1/<user>/stats/bmarkcount?api_key=<key>&start_date=2014-01-01`

and got a `502 Bad Gateway` response, however the docs say that the `start_date` and `end_date` params are just plain dates.

**Comment by mitechie** [comment]
Thanks for this Matt. I'll talk to sammyshj about it.

**Comment by sambuddhabasu** [comment]
Working on it right now.

**Comment by mitechie** [comment]
fix released
