### ISSUE TITLE
ping succeeds when it should not if user has an auth cookie 

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#344]
http://pastebin.com/Rx9UmPBU

A valid cookie is not a successful ping. The ping method needs to verify the api_key and not just tthat the user is auth'd.

**Comment by suryatech** [comment]
@mitechie http://pastebin.com/BUM3bAcj

Same paste but different expiry and privacy settings. Please refer the above alias if the original doesn't work.
