### ISSUE TITLE
The Chrome extension couldn't work

### ISSUE THREAD

**Issue by jerryleooo** [bookieio/Bookie#363]
When I click the 'Save' button of the Bookie Chrome extension, there just is a circle progressbar rolling all the time and when I logined on the bmark.us I found nothing.
I have set both the username and the api key.

**Comment by suryatech** [comment]
A quick peek suggests that something has gone wrong in the latest release. Will let you know what it is.

**Comment by mitechie** [comment]
Thanks for the report. I see the error and will have a fix up shortly. It'll take a little bit for the chrome store to process the update.

**Comment by mitechie** [comment]
I've uploaded version 0.4.16 which corrects this. Once the Chrome store processes the update it should auto upgrade everyone's extension. 

Note: you can try to force the upgrade from the "manage" section of the extensions. It has been taking 30-40minutes for the chrome web store to process new versions lately. 

Closing, but if you don't see a fix in the next hour or so please reopen this issue.

**Comment by jerryleooo** [comment]
Version 0.4.16 has fixed this issue, I tried it just now.
