### ISSUE TITLE
api_key is not able to be reset

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#373]
The idea of the api_key is that a user could generate a new one. There's tool to help generate an api key. We should have a button in the UI to generate a new one for the user and report it back as part of their account page.

**Comment by rakeshmahadasa** [comment]
So when the users clicks on the button  , a new random api will be created and old one is overwritten with the new one ryt?

Doing this one :)

**Comment by suryatech** [comment]
Yes. You are right.

**Comment by rakeshmahadasa** [comment]
Added this feature https://github.com/bookieio/Bookie/issues/374

**Comment by mitechie** [comment]
The branch there needs some more attention to land. Feature isn't quite ready. Will try to make sure we get to this soon though. It's meant to be there for users and is important.

**Comment by rakeshmahadasa** [comment]
Sure thing rick. I shouldn't have started working on suggesting tags without completing this feature ,  my bad. Will soon work on this issue.

**Comment by mitechie** [comment]
Not quite done yet, the backend is landing. Front end still needs to land.
