### ISSUE TITLE
the docs have really out of date screenshots

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#375]
We should walk through the docs and make sure to get modern screenshots of the site, extensions, etc.

**Comment by sambuddhabasu** [comment]
I would like to work on this issue.

**Comment by mitechie** [comment]
This was because the docs were pointing at my personal fork from before I moved the bookie repo to the bookieio organization. I've updated the docs config and it's much better now. I think this is good and closing this issue.
