### ISSUE TITLE
tag filtering not returning all results

### ISSUE THREAD

**Issue by widox** [bookieio/Bookie#381]
I tried searching for the tag "git", and its only returning 3 results. Two of them are new this morning, and it looks like it replaced two other ones that were there before.
https://bmark.us/widox/recent/git?count=50&page=0

I know there are more then three bmarks for git.

**Comment by widox** [comment]
Also tried the Search tab, https://bmark.us/results?search=git&content=true&search_mine=on&submit=Search  and it only returns a single result

**Comment by mitechie** [comment]
Marking this as sprint work as fulltext should get a lot of attention and we'll be rebuilding the indexes used during server updates. During that time let's make sure to keep an eye to chase this issue down.

**Comment by mitechie** [comment]
The search tab is working nice. The filter is only showing five. As your search results show, you've tagged a lot more than 4 bookmarks with the tag git.

Updating the bug description and making it not about fulltext search but the normal query filtering.

**Comment by mitechie** [comment]
The inner query of a join was missing the username clause and so it was grabbing the first 50 tagged bookmarks and then finding the ones by the user. Updated and appears to be all good now.

https://bmark.us/widox/recent/git?count=50&page=0

**Comment by widox** [comment]
:thumbsup:  thanks @mitechie!
