### ISSUE TITLE
update bookmark "add new" page with the tag suggestions like the extension

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#406]

**Comment by rakeshmahadasa** [comment]
but what information do we have ?? we dont have the url and title also ryt?? except the recent tags we have nothing when a user tries to add new bookmark on website

**Comment by mitechie** [comment]
Ah true. We can suggest it if the url when the user enters it via js. When
used send using the bookmarklet the send the url and title. The only case
is hitting the manual "add bookmark"  button.

**Comment by mitechie** [comment]
This is updated and landed. It works for bookmarklet users. The JS stuff we can look at later. I'm not 100% sure on it.
