### ISSUE TITLE
Make the API Key field on /impot not a ****** input

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#41]
(not sure what the right terminology is for password-like text entry forms)

Why? Because the API Key might be some weird combination of letters, numbers, and symbols set by a Bookie administrator and the user might be trying to type it in character by character.

Also, since it is not a password it shouldn't look like one. :)

**Comment by mitechie** [comment]
It's a password html input. Another debate. People can see you input it, so we wanted to protect it, however you don't enter it very often (only on inport and setting up your api key in the chrome extension) so the likelihood of it leaking is small.

Adding to milestone 0.2

**Comment by mitechie** [comment]
Going to close this for now. I just don't like the idea of it being visible right now. Eventually we'll get real password auth and it won't be necessary, but for now, I'd rather hide the key since it can be then used for api access from an extension
