### ISSUE TITLE
When "Content" is checked in the search box, also return title/tag hits

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#42]
The set of results from when I search without "Content" checked should be a subset of when I have "Content" checked.

Right now, I get two results when "Content" is not checked, but zero results when it is. That is unexpected :)

**Comment by mitechie** [comment]
This is true, currently the 'readable' content is a different table with its own fulltext index. We're splitting out tags into their own ui. This is going to require some thought on how to do the search. On a large set of bookmarks, searching the readable cached content might slow things down a bit so we do want to default to not searching the body of every bookmark.
