### ISSUE TITLE
502 Bad Gateway when trying to edit certain bookmarks

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#425]
http://nbviewer.ipython.org/github/rasbt/python_reference/blob/master/not_so_obvious_python_stuff.ipynb
dyladan/infinitium_rk/nodeman all have this problem
85b07ce1739f3f
created 44 minutes ago

https://www.youtube.com/watch?v=-5wpm-gesOY
a7da83b1294d65
created 1 day ago

both of those bookmarks have the issue.

**Comment by rakeshmahadasa** [comment]
![bookie recent bookmarks](https://cloud.githubusercontent.com/assets/3924151/2740203/b2818b64-c6cb-11e3-9546-efaea630c5b9.png)
I can add two bmarks which are similar , was able to access edit page for one and ended up with 502 bad gateway with other  

Hash id - 221b3535a1dd9e - 502 BadGateway
Hash id - 02e99d257604cf - Editable

**Comment by mitechie** [comment]
I'll look. The 502 is generating an error and I'll have to replicate to
see. Last time this was the tag suggestions code missing a safety check.

**Comment by mitechie** [comment]
Closing now that the updated code is released. Please let me know if you hit this again. We've got better logging in place now.
