### ISSUE TITLE
/export should be a page similar to /import with an "export now" button

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#43]
... or similar. At least have /export be a page not just a function call that returns the html.

Why, because sometimes people just click on those import/export links at the bottom without actually wanting to do the action, just curious what it is.

Also, because theoretically the /export function could take a while with large databases.

Also, because it will give us a way to tell the browswer "this is a file the user wants to download, not display as a webpage" (maybe zip the html like diigo does to force that?). If it is displayed as a webpage, some users might not know what to do from there.

Proposed text:
# Export Bookmarks

This will create an export/backup of all your bookmarks currently in Bookie. With this file, you can import your bookmarks into your browser or other web-based bookmarking services (such as Diigo, Delicious, or pinboard.in) or just save it for safe keeping (backups are always good!).

[EXPORT BUTTON]

**Comment by mitechie** [comment]
I'm not sold on this one. I like the idea of the export being a simple link people can use to script/backup their bookmarks easily. In our largest test file of 16k bookmarks the page still takes < 10s to render/load. 

I do agree that it needs to add the content-disposition and perform a download vs a visible html to the user. Adding to 0.2 milestone to fix that up.

If others disagree and want the 2 step export please speak up and I can be persuaded.
