### ISSUE TITLE
First page of bookmarks doesn't show previous / next buttons

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#437]
I'm seeing a bug where the following URL:

https://bmark.us/craig/recent/wishlist?count=50&page=0#

doesn't show me a "Next" button.

(Using Chrome 34)

**Comment by suryatech** [comment]
I did some checking and here is what i found. 
1. Visit https://bmark.us/craig/recent. Pagination works fine. 
2. Filter the results using a tag and the pagination disappears.

Checked the console for errors and everything seems to work fine.

Btw, if you remove one or more tags from the filter, the search results are updated but the URL is not re-written. 

@mitechie

**Comment by mitechie** [comment]
So I can't duplicate any issue with the next/previous buttons. As you filter, they're AND'd together and once the results is < 50 the pagination disappears. 

The url should update though. That's a bug.

**Comment by mitechie** [comment]
url is now showing the next button. Please let me know if you hit the issue again.
