### ISSUE TITLE
with_content parameter doesn't work

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#445]
on the api endpoint `/:username/bmarks` the `with_content=true` parameter doesn't appear to be doing anything as shown by the fact that the following two URLs return the exact same JSON.

https://bmark.us/api/v1/dyladan/bmarks?count=1&with_content=true
https://bmark.us/api/v1/dyladan/bmarks?count=1

**Comment by dyladan** [comment]
This may affect other endpoints as I have only tested this one. It is worth noting that all of the following routes use the same function in api.py
- `api_bmarks`
- `api_bmarks_user`
- `api_bmarks_tags`
- `api_bmarks_user_tags`

edit: tested all of the above endpoints and none of them responds to `with_content`

**Comment by dyladan** [comment]
full text is returned properly when the bmark is called using `/:username/bmark/:hash_id` endpoint

**Comment by dyladan** [comment]
if you change this line https://github.com/bookieio/Bookie/blob/develop/bookie/views/api.py#L412 to be `if 'with_content' in params and params['with_content'] != 'false':` it appears to be working on my local copy at least. I have a working branch but would like help writing the test for this.

**Comment by mitechie** [comment]
This now functions properly.
