### ISSUE TITLE
/:username/bmarks/search/:terms appears to be broken

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#449]
`https://bmark.us/api/v1/dyladan/bmarks/search/coroutines` returns no bookmarks while `https://bmark.us/api/v1/bmarks/search/coroutines` does return bookmarks, at least one of which is `username=dyladan`

**Comment by dyladan** [comment]
ignore this it's working fine

**Comment by dyladan** [comment]
reopening this since i figured out what was causing my original issue.

`https://bmark.us/api/v1/dyladan/bmarks/search/coroutines&with_content=true` returns no results
`https://bmark.us/api/v1/dyladan/bmarks/search/coroutines` does return results

`with_content=true` works fine on `/bmarks/search/:terms` endpoint but on the `/:username/bmarks/search/:terms` endpoint it appears that it thinks `&with_content=true` is a part of the search term and not a parameter.

here is the full json response for the non-working endpoint

```
{"username": "dyladan", "search_results": [], "with_content": false, "phrase": "coroutines&with_content=true", "page": 0, "result_count": 0}
```

**Comment by dyladan** [comment]
so apparently none of the params are working. they are all just a part of the search string. I found this issue and it's pretty simple fix. writing a test now

**Comment by dyladan** [comment]
do not merge this. I was misunderstanding the problem

**Comment by dyladan** [comment]
https://bmark.us/api/v1/dyladan/bmarks/search/coroutines
returns 1

https://bmark.us/api/v1/dyladan/bmarks/search/coroutines?with_content=true
returns 0 results

https://bmark.us/api/v1/bmarks/search/coroutines
returns 5 results

https://bmark.us/api/v1/bmarks/search/coroutines?with_content=true
returns 10 results

In none of these queries is the above problem where content=true was showing up in the phrase. I think that was just because i was using & instead of ?

The non-username search appears to be working as expected.

The user specific search appears to work if there are no params, but if you add `with_content=true` or `count=` params no results are returned

**Comment by dyladan** [comment]
this appears related to #450

**Comment by mitechie** [comment]
Closing as lost in history and there's something else up elsewhere.
