### ISSUE TITLE
/bmarks/search/:terms not respecting count parameter

### ISSUE THREAD

**Issue by dyladan** [bookieio/Bookie#450]
`https://bmark.us/api/v1//bmarks/search/stuff&count=2` is returning 10 bookmarks. Like #449 it appears that it is using the parameter as a part of the search term as shown by the JSON returned `"phrase": "stuff&count=2"`

**Comment by dyladan** [comment]
WOW i just realized what was causing this. I was using & instead of ?

**Comment by dyladan** [comment]
ok so there is still an issue here

https://bmark.us/api/v1/bmarks/search/coroutines
returns 5 results

https://bmark.us/api/v1/bmarks/search/coroutines?count=2
returns 2 results

https://bmark.us/api/v1/dyladan/bmarks/search/coroutines
returns 1 result

https://bmark.us/api/v1/dyladan/bmarks/search/coroutines?count=1
returns 0 results

**Comment by dyladan** [comment]
this appears related to #449

**Comment by mitechie** [comment]
Hmm, so the bug here with the count is corrected, but the number of results seems shy for your bookmarks. I'm closing this bug but looking into matching up the number of fulltext indexed bookmarks with the number of total bookmarks.
