### ISSUE TITLE
Deleting bookmark throws dependency error

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#46]
When deleting a bookmark, it throws the following error:

URL: http://127.0.0.1:6543/bmark/delete
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/WebError-0.10.3-py2.6.egg/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/repoze.tm2-1.0b1-py2.6.egg/repoze/tm/**init**.py', line 44 in **call**
  self.commit()
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/repoze.tm2-1.0b1-py2.6.egg/repoze/tm/**init**.py', line 52 in commit
  t.commit()
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/transaction-1.1.1-py2.6.egg/transaction/_transaction.py', line 329 in commit
  self._commitResources()
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/transaction-1.1.1-py2.6.egg/transaction/_transaction.py', line 441 in _commitResources
  rm.tpc_begin(self)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/zope.sqlalchemy-0.6.1-py2.6.egg/zope/sqlalchemy/datamanager.py', line 87 in tpc_begin
  self.session.flush()
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/session.py', line 1388 in flush
  self._flush(objects)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/session.py', line 1469 in _flush
  flush_context.execute()
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/unitofwork.py', line 302 in execute
  rec.execute(self)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/unitofwork.py', line 402 in execute
  self.dependency_processor.process_deletes(uow, states)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/dependency.py', line 488 in process_deletes
  uowcommit, False)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/dependency.py', line 532 in _synchronize
  sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
File '/home/craig/.virtualenvs/bookie/lib/python2.6/site-packages/SQLAlchemy-0.6.6-py2.6.egg/sqlalchemy/orm/sync.py', line 41 in clear
  (r, mapperutil.state_str(dest))
AssertionError: Dependency rule tried to blank-out primary key column 'readable.hash_id' on instance '<Readable at 0x2bd3390>'

**Comment by mitechie** [comment]
Added the cascade rule for Hashed->Readable. 

Need to add a unit test that not only creates a new bmark, but stored the readable content for it and make sure that removing the bmark cascades down to the readable content.
