### ISSUE TITLE
ghost bmarks

### ISSUE THREAD

**Issue by esacteksab** [bookieio/Bookie#482]
Steps to reproduce:

1) https://bmark.us/basketcase/new
2) enter URL
3) enter tags
4) save

Browser: Version 35.0.1916.153
OS: 

```
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:    14.04
Codename:   trusty
➜  ~  uname -a
Linux esacteksab 3.13.0-30-generic #54-Ubuntu SMP Mon Jun 9 22:45:01 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

This will redirect to https://bmark.us/basketcase and you will see [No Title] and an eye, but it's a ghost.

**Comment by mitechie** [comment]
I think this is solved now. Please reopen if you see it again.
