### ISSUE TITLE
problem with firefox app when using nginx proxy to paster

### ISSUE THREAD

**Issue by xavierle** [bookieio/Bookie#497]
i am testing bookie since some days.

1
i first ran the tests using the adress 
myserveradress.com:6543

in that case
i can add bookmarks from the interface, from firefox and chrome apps and also android.

2
later
i ran the same tests from the wanted adress :
myserveradress.com
using the easy way "Nginx proxy to Paster"

in that case i can add bookmarks from the web interface, the android app and the chromium app

but not from firefox app

i will make another try during the day

**Comment by mitechie** [comment]
Hmm, not sure on this one. Can you verify if the requests made it to the application by checking the actual log on the pyramid/python app? I can't think of anything different on the firefox extension. Does it verify that the config is correct and a ping command works? Maybe it's more that there's a typo or the like on the config in the FF extension?

**Comment by xavierle** [comment]
at the end i made another try today
after restarting everything

 it was working fine

**Comment by mitechie** [comment]
Thanks for checking it out. Closing.
