### ISSUE TITLE
problem with sending emails

### ISSUE THREAD

**Issue by xavierle** [bookieio/Bookie#498]
actually i feel that sending emails from bookie is not that easy

(i am relatively new to python and much more  used to php applications)

most public installation of bookie do not send the emails

on https://bmark.us/dashboard

i shall have ad several users from me
and i never received any activation emails

https://lib3.net/bookie/dashboard
on this installation the same

on my test installation, I did follow

pip install inbox which ran smoothly

pip install inbox : 

Requirement already satisfied (use --upgrade to upgrade): inbox in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/dist-packages (from inbox)
Requirement already satisfied (use --upgrade to upgrade): logbook in /usr/local/lib/python2.7/dist-packages (from inbox)
Requirement already satisfied (use --upgrade to upgrade): greenlet in /usr/local/lib/python2.7/dist-packages (from gevent->inbox)
Cleaning up...

but then the command "make smtp " is giving me this error

bin/python scripts/misc/smtpsink.py
Traceback (most recent call last):
  File "scripts/misc/smtpsink.py", line 9, in <module>
    from inbox import Inbox
ImportError: No module named inbox
make: **\* [smtp] Erreur 1

any idea about what i did wrong ?

**Comment by mitechie** [comment]
The 'make smtp' target is purely for development purposes and does not actually send out any email.

To configure email, you need to setup an smtp server on your machine running bookie and configure it via the bookie.ini file:

https://github.com/bookieio/Bookie/blob/develop/sample.ini#L17

I use a tool called msmtp to function as a smtp server on the bmark.us host and then it sends email out through my normal email account.

**Comment by xavierle** [comment]
i will have a try that way

but actually i never received the emails from bmark.us

**Comment by mitechie** [comment]
I've updated the server and created a new test account on there to check that emails are going out. Please try again or let me know if you have any issues. Closing for now.

**Comment by xavierle** [comment]
Forgotten Password

```
Email
```

Forgotten Password

You've already marked your account for reactivation. Please check your email for the reactivation link. Make sure to check your spam folder.

but no email has been received
(i registered with a gmail)

**Comment by mitechie** [comment]
Let me know (irc channel or email or something) what the email address is and I'll remove it from the system and it'll be cleared to re-add.
