### ISSUE TITLE
how to hide pyramid debugtoolbar

### ISSUE THREAD

**Issue by xavierle** [bookieio/Bookie#499]
if i have a small experience in python
i am definitively new to pyramid framework

actually in all the bookie pages there is a button that to opens the pyramid debug toolbar

this seems to be a very useful tool for debugging
but i would like to hide it to normal users because it really gives too much information to the public

how shall i do that ?

is this  related to the pramid debugtoolbar  ?

or to the bookie application ?

**Comment by mitechie** [comment]
To disable it remove the debug toolbar middleware in the bookie.ini file. You can see it in the sample.ini here

https://github.com/bookieio/Bookie/blob/develop/sample.ini#L9

**Comment by xavierle** [comment]
ok thank you for the tip

maybe to be included in the readthedocs page
