### ISSUE TITLE
search is missing content

### ISSUE THREAD

**Issue by craigmaloney** [bookieio/Bookie#509]
https://bmark.us/recent/openmetalcast?count=50&page=0 <- Shows 8 entries

https://bmark.us/results/openmetalcast?count=32&page=0# <- Shows two entries.

**Comment by mitechie** [comment]
I've added the fulltext stats to the dashboard:

https://bookie.io/dashboard

It looks like we're missing a lot of content from the fulltext index. I've added a background celery job to find missing bookmarks and update 500 of them at a time every 10min. It looks like it should take a little over a full day to catch back up if all goes well. 

Let's check this tomorrow and see if the index is up to date and if so, if your search link is a lot better.

**Comment by mitechie** [comment]
This is better now and the search works:

https://bookie.io/results?search=openmetalcast&content=true&search_mine=on&submit=Search

There is still the issue #507 and so to get this I had to check the box for 'search only my bookmarks' which is clearly not 'only searching mine'. 

That'll be the next search bug up.
