### ISSUE TITLE
bookie should not use background queue for activation emails

### ISSUE THREAD

**Issue by sahilbabbar** [bookieio/Bookie#514]
Hi, 

I recently signed up to Bookie and didn't got the confirmation email in the inbox. So, keeping part the problem, I was wondering that what if Bookie could talk to Twisted Web Engine and use its Mail Client protocols to do it lightening fast!

**Comment by mitechie** [comment]
Sorry you had problems signing up. Do you recall when you attempted to sign up? What email did you sign up with? I'd like to check the logs and see if things hit an issue.

Right now bookie.io sends the email out via a background task. We've recently moved to new larger servers and I'm wondering if you're signup had issues in the moving process.

I'm not sure about bringing twisted into the codebase to send emails. I do think moving them to the celery backend was a bad move as it puts signups into the queue with large running tasks like bookmark imports and the like. I'm up for making it a better process, but I'm not sure adding the twisted dependency is the right way forward.

**Comment by sahilbabbar** [comment]
I signed up with a @live email id. Some services do behave abnormally with Microsoft domain names like hotmail and live and often the emails related to those services are junked automatically probably due to their more stricter junk filter. 

This happened to Bookie as well as the activating email came to junk almost after 2 hrs I signed up. 

I am exploring Twisted as a part of my Research Work, so I will let you know how it shall be helpful to Bookie.

**Comment by tino** [comment]
I am also not receiving any mail. I signed up with (github username)db@gmail.com, and tried again with  (github username)db+new@gmail.com but to no avail.

I don't think a complete framework as twisted is needed to send emails. Best solution I have seen so far is running Exim as a local MTA. That way sending mails from the request happen practically instantaneous, and Exim can queue and retry if necessary.

**Comment by sahilbabbar** [comment]
We can use only the IMAP4 client library from Twisted.

**Comment by tino** [comment]
IMAP is for retrieving and storing email, which is probably not necessary
here. Python has a builtin lib (smtplib) for sending email. The only thing
is that you want to offload that from the request-response cycle in case
the other end is slow or non-responsive. For that we can use an MTA, or a
task queue like celery (as is done atm).

@mitechie, I did receive both mails. Just took a couple of hours...

**Comment by mitechie** [comment]
@tino I see your signup requests, and I can verify in the log that the emails went out and were send out with a 'ok' status. 

They went out at Sep 19 11:36:55 and Sep 19 11:43:11

Please check the spam folder and see if it arrived at all. The subject is:

```
Enable your Bookie account
```

I'm not sure what I can do on this end as everything seems to be working properly from here.

**Comment by mitechie** [comment]
@sahilbabbar I also see your signup email in my logs and it also went out without error from the smtp server.

It was sent Sep 18 23:49:11 and has the same title.

**Comment by sahilbabbar** [comment]
Thanks for checking @mitechie & I already told that I got the confirmation email roughly 2 hours after I signed up. So, the whole point is to increase this email workflow to remove this lag.

**Comment by mitechie** [comment]
@sahilbabbar oh sorry I completely missed that. Yes, that's due to the message queue and the fact that we just have a single background task queue. It's less than ideal. Glad you got the email and apologize for the delay. I'll leave this bug open as a note that moving that work back into the main app thread is probably the best way to fix things.

**Comment by alexlehm** [comment]
Does the background queue use a local smtp server or is this directly sent to the recipient MX server from the queue? In the first case, the mail delivery should work regardless of how long the delivery takes from the server to the recipient server, in the 2nd case, if the queue is processed sequentially, if one mail is stuck, the next ones will hang in the queue.

(I am usually in favour of solution 1, leave the difficult job to postfix, unless you have a mail provider like mailgun)

**Comment by sakshamsaxena** [comment]
Its been almost over 8 hours since i signed up and haven't yet received the mail. I can wait, no problem, but yeah this issue needs to get some priority...

**Comment by mitechie** [comment]
@sakshamsaxena sorry, looks like the celery queue got hung up. I've restarted it and it's not processing like the wind. I'll keep an eye on it and you should see the email shortly.

**Comment by sahilbabbar** [comment]
Closed due to inactivity.
