### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by qiuwei** [bookieio/Bookie#560]
I want to use [Sourcegraph](https://sourcegraph.com) for Bookie code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/bookieio/Bookie. (It should only take 30 seconds.)

Thank you!

**Comment by mitechie** [comment]
Done 

https://sourcegraph.com/search?q=github.com%2Fbookieio%2FBookie+
