### ISSUE TITLE
Uploading 1.6MB delicious export said to be too large...

### ISSUE THREAD

**Issue by burkesquires** [bookieio/Bookie#561]
I have tried uploading my 1.6 MB delicious export and get eh following error:

413 Request Entity Too Large

nginx/1.4.6 (Ubuntu)

I tried but could not update an html file.

**Comment by craigmaloney** [comment]
Hello,

Would it be possible to send your export to one of the developers or attach to the ticket? If so please do so we can see if we can replicate this.

Thanks!

**Comment by burkesquires** [comment]
Please find the file attached.

Cheers,

Burke

**Comment by craigmaloney** [comment]
Hm, I'm not seeing it attached. Perhaps we'll need to use something like Dropbox instead?

Thanks!

**Comment by dzmitry-lahoda** [comment]
I raised same issue on Google Groups and file attached here https://groups.google.com/forum/#!topic/bookie_bookmarks/Svm5IlMAAFw

**Comment by mitechie** [comment]
This is going to be constraints on the server running bookie.io. As bookie.io is shutting down on July 5th I'm not going to worry about a fix at this time. It's not native to bookie itself, but the services (nginx) and the settings of it that bookie is hosted behind.
