### ISSUE TITLE
import from Firefox dump

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#71]
Tweaked the google import to work for a Firefox html dump. It doesn't dump tags though. The <h3> is the directory of the bookmark. The backup/json dump has the info, but it's very tied to the db table relation.

Basically, anything of type 2 is tags. It's nested and you have to sort.

**Comment by mitechie** [comment]
http://stackoverflow.com/questions/464516/firefox-bookmarks-sqlite-structure

describes the structure a bit

**Comment by silopolis** [comment]
This is maybe the feature I miss most but may be I can upload to delicious or google and then import in bookie... Btw, delicious behaviour of converting folders to tags is cool for people like me that took years before understanding the power of tagging ;-)

**Comment by mitechie** [comment]
If you have a firefox bookmarks json dump you don't mind sharing I'd love to get a copy and we can look at adding an importer. It's usually not terribly hard. We just need to write a custom importer class here:

https://github.com/mitechie/Bookie/blob/develop/bookie/lib/importer.py

**Comment by mitechie** [comment]
Amazingly updated and on the live site. Woot!
