### ISSUE TITLE
Missing fabric from maverick instructions

### ISSUE THREAD

**Issue by teeks99** [bookieio/Bookie#81]
In the documentation for the install on ubuntu maverick, there is a dependency on the fabric tool, but the pre-reqs that were listed don't grab it.

Maybe: 
$ sudo apt-get install build-essential libxslt1-dev libxml2-dev python-dev fabric
?

**Comment by teeks99** [comment]
Git is missing also. 

$ sudo apt-get install build-essential libxslt1-dev libxml2-dev python-dev fabric git

**Comment by mitechie** [comment]
Fabric is installed via easy_install or pip. It's listed in the requirements.txt file and if you're using the bootstrap.py file it should auto download. If you're installing manually you'll hit it in the install step 

```
pip install -r requirements.txt 
```

You're right that git is implied. I've added that to the docs in the apt-get install step.
