### ISSUE TITLE
Import Chrome Bookmarks

### ISSUE THREAD

**Issue by brousch** [bookieio/Bookie#84]
I would like to import my Chrome bookmarks. An example of a Chrome bookmark export can be found at http://dl.dropbox.com/u/101667/bookmarks_6_17_11.html

**Comment by mitechie** [comment]
The current code base supports importing chrome exports. I'll work on updating the docs to note this. 

Be aware, Chrome doesn't support tags, so the folders become tags from the export. Search works well though. In the future we'll get a mass edit interface that will help users add tags to bookmarks for cases like this.
