### ISSUE TITLE
start running daily cron jobs to store counts per user

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#87]
We want to be able to provide some trend graph info to users. We want to run daily stats on how many total bookmarks and tags they have in the system.

Then we can add a stats page on their account pages that can track that over time. Might be interesting, especially once we start allowing trimming of bad links/etc. Might stick that in there as well. Count the number of readable that ended in 404, unresolved, etc.

**Comment by mitechie** [comment]
I basically want to get celery and rabbitmq going. These tasks will be fired off via scheduled jobs there. 

So the idea would be to create a 24hr task that inits a task per user to gather their stats into the stats log.

**Comment by mitechie** [comment]
This should be run from the new celery system. Basically a scheduled item to calc the total for each user that then fires of subtask items for each user in the system to go do the actual counting.

**Comment by sambuddhabasu** [comment]
I am working on this issue.

**Comment by mitechie** [comment]
This is landed and bookmark counts should start today.
