### ISSUE TITLE
update api to provide stats information

### ISSUE THREAD

**Issue by mitechie** [bookieio/Bookie#88]
Might be cool to provide a /stats api url for things like number of bookmarks, tags, etc in the last seven days and what not. Then the mobile ui could show some nice trends/activity info. I know I'd like it, but other users might as well and it's all non-personal data so should be good to share via api.

**Comment by sambuddhabasu** [comment]
I would like to work on this issue.
Already the /dashborad api url shows number of bookmarks and number of unique urls. So, the other things could be added to the same api.
