### ISSUE TITLE
Include year in search results

### ISSUE THREAD

**Issue by greggrossmeier** [bookieio/Bookie#96]
When doing a search that turns up a many bookmarks from a long time span, it is helpful to know which June 20th the URL was bookmarked in, eg: https://bmark.us/results?search=security&submit=Go

I assume we could just go all Y2K on it and add `'11` after the month in the red bar area so it reads, eg: `June '11`

**Comment by mitechie** [comment]
So this is something I thought a ton about when working on the calendar graphic. Usually, the page shows very recent bookmarks and it should be a long run to older bookmarks that would change the year on the view.

However, I completely agree that in search that is probably the one time that you might hit long time spans between bookmarks. 

So two parts. 
- I'll definitely look at adding the year, on a search results perhaps. That way most of the default views don't clutter. 
- Did you know that if you hover over the month part of the calendar icon it displays the full d/m/y? It's not very 'glimpse-able' but I wonder if that might have met the use case you hit?

**Comment by greggrossmeier** [comment]
1: Perfect.
2: I did not! Huh. I think that should definitely stay, of course :) Thanks!

**Comment by craigmaloney** [comment]
Could also get real fancy, and for anything more than a year old, add the year (ie: Jun 10, '10, Jun 10, '09, etc)
