### ISSUE TITLE
Password Reset does not indicate an action happened

### ISSUE THREAD

**Issue by brousch** [bookieio/Bookie#98]
After clicking the Reset button for resetting my password, it's not clear that the action was successful. The site should redirect to somewhere or display a "message sent" notification.

**Comment by mitechie** [comment]
It now does this. It also displays a message if you attempt to re-'forgot password' it that you should already have an email and to please check your spam folder. 

I'm going to leave this at that for now, at some point we might want to be able to 'resubmit' or something to get an additional copy of hte email, but I don't want to allow some sort of spamming to take place by someone over and over marking for another copy.
